#server.port=8888
server:
  port: 8888

# MySQL
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb
#spring.datasource.username=test
#spring.datasource.password=1212

#spring.application.name=day03
spring:
  application:
    name: day03

--- # \uAD6C\uBD84\uD558\uAE30 \uC27D\uAC8C
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/testdb
    username: test
    password: 1212


# mybatis mapper
#mybatis.mapper-locations=classpath:mapper/*.xml
# alias
#  mybatis.type-aliases-package=com.mbc.day03.domain

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mbc.day03.domain